//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Client.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IServer", Namespace="http://tempuri.org/")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDataUsingDataContractOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginDesignerOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoginAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddDesignInDLOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddShoeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOrdersListOperationCompleted;
        
        private System.Threading.SendOrPostCallback ShowShoeStatusOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateaOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback GenerateIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback PlaceOrderOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateComplaintOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddComplaintOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllComplaintsOperationCompleted;
        
        private System.Threading.SendOrPostCallback ApproveAllOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetApprovedOrdersOperationCompleted;
        
        private System.Threading.SendOrPostCallback ClearAllOrdersOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::Client.Properties.Settings.Default.Client_localhost_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetDataUsingDataContractCompletedEventHandler GetDataUsingDataContractCompleted;
        
        /// <remarks/>
        public event LoginDesignerCompletedEventHandler LoginDesignerCompleted;
        
        /// <remarks/>
        public event LoginAdminCompletedEventHandler LoginAdminCompleted;
        
        /// <remarks/>
        public event AddDesignInDLCompletedEventHandler AddDesignInDLCompleted;
        
        /// <remarks/>
        public event AddShoeCompletedEventHandler AddShoeCompleted;
        
        /// <remarks/>
        public event GetOrdersListCompletedEventHandler GetOrdersListCompleted;
        
        /// <remarks/>
        public event ShowShoeStatusCompletedEventHandler ShowShoeStatusCompleted;
        
        /// <remarks/>
        public event CreateaOrderCompletedEventHandler CreateaOrderCompleted;
        
        /// <remarks/>
        public event GenerateIdCompletedEventHandler GenerateIdCompleted;
        
        /// <remarks/>
        public event PlaceOrderCompletedEventHandler PlaceOrderCompleted;
        
        /// <remarks/>
        public event CreateComplaintCompletedEventHandler CreateComplaintCompleted;
        
        /// <remarks/>
        public event AddComplaintCompletedEventHandler AddComplaintCompleted;
        
        /// <remarks/>
        public event GetAllComplaintsCompletedEventHandler GetAllComplaintsCompleted;
        
        /// <remarks/>
        public event ApproveAllOrdersCompletedEventHandler ApproveAllOrdersCompleted;
        
        /// <remarks/>
        public event GetApprovedOrdersCompletedEventHandler GetApprovedOrdersCompleted;
        
        /// <remarks/>
        public event ClearAllOrdersCompletedEventHandler ClearAllOrdersCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string GetData(int value, [System.Xml.Serialization.XmlIgnoreAttribute()] bool valueSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        value,
                        valueSpecified});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified) {
            this.GetDataAsync(value, valueSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(int value, bool valueSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        value,
                        valueSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GetDataUsingDataContract", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public CompositeType GetDataUsingDataContract([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] CompositeType composite) {
            object[] results = this.Invoke("GetDataUsingDataContract", new object[] {
                        composite});
            return ((CompositeType)(results[0]));
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite) {
            this.GetDataUsingDataContractAsync(composite, null);
        }
        
        /// <remarks/>
        public void GetDataUsingDataContractAsync(CompositeType composite, object userState) {
            if ((this.GetDataUsingDataContractOperationCompleted == null)) {
                this.GetDataUsingDataContractOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataUsingDataContractOperationCompleted);
            }
            this.InvokeAsync("GetDataUsingDataContract", new object[] {
                        composite}, this.GetDataUsingDataContractOperationCompleted, userState);
        }
        
        private void OnGetDataUsingDataContractOperationCompleted(object arg) {
            if ((this.GetDataUsingDataContractCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataUsingDataContractCompleted(this, new GetDataUsingDataContractCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/LoginDesigner", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LoginDesigner([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass, out bool LoginDesignerResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LoginDesignerResultSpecified) {
            object[] results = this.Invoke("LoginDesigner", new object[] {
                        name,
                        pass});
            LoginDesignerResult = ((bool)(results[0]));
            LoginDesignerResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void LoginDesignerAsync(string name, string pass) {
            this.LoginDesignerAsync(name, pass, null);
        }
        
        /// <remarks/>
        public void LoginDesignerAsync(string name, string pass, object userState) {
            if ((this.LoginDesignerOperationCompleted == null)) {
                this.LoginDesignerOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginDesignerOperationCompleted);
            }
            this.InvokeAsync("LoginDesigner", new object[] {
                        name,
                        pass}, this.LoginDesignerOperationCompleted, userState);
        }
        
        private void OnLoginDesignerOperationCompleted(object arg) {
            if ((this.LoginDesignerCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginDesignerCompleted(this, new LoginDesignerCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/LoginAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void LoginAdmin([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string name, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string pass, out bool LoginAdminResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool LoginAdminResultSpecified) {
            object[] results = this.Invoke("LoginAdmin", new object[] {
                        name,
                        pass});
            LoginAdminResult = ((bool)(results[0]));
            LoginAdminResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void LoginAdminAsync(string name, string pass) {
            this.LoginAdminAsync(name, pass, null);
        }
        
        /// <remarks/>
        public void LoginAdminAsync(string name, string pass, object userState) {
            if ((this.LoginAdminOperationCompleted == null)) {
                this.LoginAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoginAdminOperationCompleted);
            }
            this.InvokeAsync("LoginAdmin", new object[] {
                        name,
                        pass}, this.LoginAdminOperationCompleted, userState);
        }
        
        private void OnLoginAdminOperationCompleted(object arg) {
            if ((this.LoginAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoginAdminCompleted(this, new LoginAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/AddDesignInDL", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddDesignInDL([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Image img) {
            this.Invoke("AddDesignInDL", new object[] {
                        img});
        }
        
        /// <remarks/>
        public void AddDesignInDLAsync(Image img) {
            this.AddDesignInDLAsync(img, null);
        }
        
        /// <remarks/>
        public void AddDesignInDLAsync(Image img, object userState) {
            if ((this.AddDesignInDLOperationCompleted == null)) {
                this.AddDesignInDLOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddDesignInDLOperationCompleted);
            }
            this.InvokeAsync("AddDesignInDL", new object[] {
                        img}, this.AddDesignInDLOperationCompleted, userState);
        }
        
        private void OnAddDesignInDLOperationCompleted(object arg) {
            if ((this.AddDesignInDLCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddDesignInDLCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/AddShoe", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddShoe([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string m, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string s, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string b, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string l) {
            this.Invoke("AddShoe", new object[] {
                        m,
                        s,
                        b,
                        l});
        }
        
        /// <remarks/>
        public void AddShoeAsync(string m, string s, string b, string l) {
            this.AddShoeAsync(m, s, b, l, null);
        }
        
        /// <remarks/>
        public void AddShoeAsync(string m, string s, string b, string l, object userState) {
            if ((this.AddShoeOperationCompleted == null)) {
                this.AddShoeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddShoeOperationCompleted);
            }
            this.InvokeAsync("AddShoe", new object[] {
                        m,
                        s,
                        b,
                        l}, this.AddShoeOperationCompleted, userState);
        }
        
        private void OnAddShoeOperationCompleted(object arg) {
            if ((this.AddShoeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddShoeCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GetOrdersList", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
        public Order[] GetOrdersList() {
            object[] results = this.Invoke("GetOrdersList", new object[0]);
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        public void GetOrdersListAsync() {
            this.GetOrdersListAsync(null);
        }
        
        /// <remarks/>
        public void GetOrdersListAsync(object userState) {
            if ((this.GetOrdersListOperationCompleted == null)) {
                this.GetOrdersListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOrdersListOperationCompleted);
            }
            this.InvokeAsync("GetOrdersList", new object[0], this.GetOrdersListOperationCompleted, userState);
        }
        
        private void OnGetOrdersListOperationCompleted(object arg) {
            if ((this.GetOrdersListCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOrdersListCompleted(this, new GetOrdersListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/ShowShoeStatus", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ShowShoeStatus([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string m, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string s, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string b, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string l) {
            object[] results = this.Invoke("ShowShoeStatus", new object[] {
                        m,
                        s,
                        b,
                        l});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ShowShoeStatusAsync(string m, string s, string b, string l) {
            this.ShowShoeStatusAsync(m, s, b, l, null);
        }
        
        /// <remarks/>
        public void ShowShoeStatusAsync(string m, string s, string b, string l, object userState) {
            if ((this.ShowShoeStatusOperationCompleted == null)) {
                this.ShowShoeStatusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnShowShoeStatusOperationCompleted);
            }
            this.InvokeAsync("ShowShoeStatus", new object[] {
                        m,
                        s,
                        b,
                        l}, this.ShowShoeStatusOperationCompleted, userState);
        }
        
        private void OnShowShoeStatusOperationCompleted(object arg) {
            if ((this.ShowShoeStatusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ShowShoeStatusCompleted(this, new ShowShoeStatusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/CreateaOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Order CreateaOrder() {
            object[] results = this.Invoke("CreateaOrder", new object[0]);
            return ((Order)(results[0]));
        }
        
        /// <remarks/>
        public void CreateaOrderAsync() {
            this.CreateaOrderAsync(null);
        }
        
        /// <remarks/>
        public void CreateaOrderAsync(object userState) {
            if ((this.CreateaOrderOperationCompleted == null)) {
                this.CreateaOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateaOrderOperationCompleted);
            }
            this.InvokeAsync("CreateaOrder", new object[0], this.CreateaOrderOperationCompleted, userState);
        }
        
        private void OnCreateaOrderOperationCompleted(object arg) {
            if ((this.CreateaOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateaOrderCompleted(this, new CreateaOrderCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GenerateId", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void GenerateId(out int GenerateIdResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool GenerateIdResultSpecified) {
            object[] results = this.Invoke("GenerateId", new object[0]);
            GenerateIdResult = ((int)(results[0]));
            GenerateIdResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void GenerateIdAsync() {
            this.GenerateIdAsync(null);
        }
        
        /// <remarks/>
        public void GenerateIdAsync(object userState) {
            if ((this.GenerateIdOperationCompleted == null)) {
                this.GenerateIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGenerateIdOperationCompleted);
            }
            this.InvokeAsync("GenerateId", new object[0], this.GenerateIdOperationCompleted, userState);
        }
        
        private void OnGenerateIdOperationCompleted(object arg) {
            if ((this.GenerateIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GenerateIdCompleted(this, new GenerateIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/PlaceOrder", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void PlaceOrder([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Order o) {
            this.Invoke("PlaceOrder", new object[] {
                        o});
        }
        
        /// <remarks/>
        public void PlaceOrderAsync(Order o) {
            this.PlaceOrderAsync(o, null);
        }
        
        /// <remarks/>
        public void PlaceOrderAsync(Order o, object userState) {
            if ((this.PlaceOrderOperationCompleted == null)) {
                this.PlaceOrderOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPlaceOrderOperationCompleted);
            }
            this.InvokeAsync("PlaceOrder", new object[] {
                        o}, this.PlaceOrderOperationCompleted, userState);
        }
        
        private void OnPlaceOrderOperationCompleted(object arg) {
            if ((this.PlaceOrderCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PlaceOrderCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/CreateComplaint", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Complaint CreateComplaint() {
            object[] results = this.Invoke("CreateComplaint", new object[0]);
            return ((Complaint)(results[0]));
        }
        
        /// <remarks/>
        public void CreateComplaintAsync() {
            this.CreateComplaintAsync(null);
        }
        
        /// <remarks/>
        public void CreateComplaintAsync(object userState) {
            if ((this.CreateComplaintOperationCompleted == null)) {
                this.CreateComplaintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateComplaintOperationCompleted);
            }
            this.InvokeAsync("CreateComplaint", new object[0], this.CreateComplaintOperationCompleted, userState);
        }
        
        private void OnCreateComplaintOperationCompleted(object arg) {
            if ((this.CreateComplaintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateComplaintCompleted(this, new CreateComplaintCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/AddComplaint", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AddComplaint([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] Complaint c) {
            this.Invoke("AddComplaint", new object[] {
                        c});
        }
        
        /// <remarks/>
        public void AddComplaintAsync(Complaint c) {
            this.AddComplaintAsync(c, null);
        }
        
        /// <remarks/>
        public void AddComplaintAsync(Complaint c, object userState) {
            if ((this.AddComplaintOperationCompleted == null)) {
                this.AddComplaintOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddComplaintOperationCompleted);
            }
            this.InvokeAsync("AddComplaint", new object[] {
                        c}, this.AddComplaintOperationCompleted, userState);
        }
        
        private void OnAddComplaintOperationCompleted(object arg) {
            if ((this.AddComplaintCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddComplaintCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GetAllComplaints", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
        public Complaint[] GetAllComplaints() {
            object[] results = this.Invoke("GetAllComplaints", new object[0]);
            return ((Complaint[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllComplaintsAsync() {
            this.GetAllComplaintsAsync(null);
        }
        
        /// <remarks/>
        public void GetAllComplaintsAsync(object userState) {
            if ((this.GetAllComplaintsOperationCompleted == null)) {
                this.GetAllComplaintsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllComplaintsOperationCompleted);
            }
            this.InvokeAsync("GetAllComplaints", new object[0], this.GetAllComplaintsOperationCompleted, userState);
        }
        
        private void OnGetAllComplaintsOperationCompleted(object arg) {
            if ((this.GetAllComplaintsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllComplaintsCompleted(this, new GetAllComplaintsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/ApproveAllOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ApproveAllOrders() {
            this.Invoke("ApproveAllOrders", new object[0]);
        }
        
        /// <remarks/>
        public void ApproveAllOrdersAsync() {
            this.ApproveAllOrdersAsync(null);
        }
        
        /// <remarks/>
        public void ApproveAllOrdersAsync(object userState) {
            if ((this.ApproveAllOrdersOperationCompleted == null)) {
                this.ApproveAllOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnApproveAllOrdersOperationCompleted);
            }
            this.InvokeAsync("ApproveAllOrders", new object[0], this.ApproveAllOrdersOperationCompleted, userState);
        }
        
        private void OnApproveAllOrdersOperationCompleted(object arg) {
            if ((this.ApproveAllOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ApproveAllOrdersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/GetApprovedOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
        public Order[] GetApprovedOrders() {
            object[] results = this.Invoke("GetApprovedOrders", new object[0]);
            return ((Order[])(results[0]));
        }
        
        /// <remarks/>
        public void GetApprovedOrdersAsync() {
            this.GetApprovedOrdersAsync(null);
        }
        
        /// <remarks/>
        public void GetApprovedOrdersAsync(object userState) {
            if ((this.GetApprovedOrdersOperationCompleted == null)) {
                this.GetApprovedOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetApprovedOrdersOperationCompleted);
            }
            this.InvokeAsync("GetApprovedOrders", new object[0], this.GetApprovedOrdersOperationCompleted, userState);
        }
        
        private void OnGetApprovedOrdersOperationCompleted(object arg) {
            if ((this.GetApprovedOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetApprovedOrdersCompleted(this, new GetApprovedOrdersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IServer/ClearAllOrders", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ClearAllOrders() {
            this.Invoke("ClearAllOrders", new object[0]);
        }
        
        /// <remarks/>
        public void ClearAllOrdersAsync() {
            this.ClearAllOrdersAsync(null);
        }
        
        /// <remarks/>
        public void ClearAllOrdersAsync(object userState) {
            if ((this.ClearAllOrdersOperationCompleted == null)) {
                this.ClearAllOrdersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnClearAllOrdersOperationCompleted);
            }
            this.InvokeAsync("ClearAllOrders", new object[0], this.ClearAllOrdersOperationCompleted, userState);
        }
        
        private void OnClearAllOrdersOperationCompleted(object arg) {
            if ((this.ClearAllOrdersCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ClearAllOrdersCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public partial class CompositeType {
        
        private bool boolValueField;
        
        private bool boolValueFieldSpecified;
        
        private string stringValueField;
        
        /// <remarks/>
        public bool BoolValue {
            get {
                return this.boolValueField;
            }
            set {
                this.boolValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool BoolValueSpecified {
            get {
                return this.boolValueFieldSpecified;
            }
            set {
                this.boolValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string StringValue {
            get {
                return this.stringValueField;
            }
            set {
                this.stringValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public partial class Complaint {
        
        private string cellField;
        
        private string complaint_TextField;
        
        private string emailField;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Cell {
            get {
                return this.cellField;
            }
            set {
                this.cellField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Complaint_Text {
            get {
                return this.complaint_TextField;
            }
            set {
                this.complaint_TextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public partial class Shoe {
        
        private string brandField;
        
        private string lacesField;
        
        private string mainColorField;
        
        private string sideColorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Brand {
            get {
                return this.brandField;
            }
            set {
                this.brandField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Laces {
            get {
                return this.lacesField;
            }
            set {
                this.lacesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string MainColor {
            get {
                return this.mainColorField;
            }
            set {
                this.mainColorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string SideColor {
            get {
                return this.sideColorField;
            }
            set {
                this.sideColorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/Server")]
    public partial class Order {
        
        private string adressField;
        
        private System.DateTime deliveryDateField;
        
        private bool deliveryDateFieldSpecified;
        
        private int idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private Shoe shoeField;
        
        private bool statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Adress {
            get {
                return this.adressField;
            }
            set {
                this.adressField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime DeliveryDate {
            get {
                return this.deliveryDateField;
            }
            set {
                this.deliveryDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeliveryDateSpecified {
            get {
                return this.deliveryDateFieldSpecified;
            }
            set {
                this.deliveryDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Shoe Shoe {
            get {
                return this.shoeField;
            }
            set {
                this.shoeField = value;
            }
        }
        
        /// <remarks/>
        public bool Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified {
            get {
                return this.statusFieldSpecified;
            }
            set {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/System.Drawing")]
    public partial class Image {
        
        private System.Xml.XmlElement[] anyField;
        
        private System.Xml.XmlQualifiedName factoryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute()]
        public System.Xml.XmlElement[] Any {
            get {
                return this.anyField;
            }
            set {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://schemas.microsoft.com/2003/10/Serialization/")]
        public System.Xml.XmlQualifiedName FactoryType {
            get {
                return this.factoryTypeField;
            }
            set {
                this.factoryTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetDataUsingDataContractCompletedEventHandler(object sender, GetDataUsingDataContractCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataUsingDataContractCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataUsingDataContractCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public CompositeType Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((CompositeType)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LoginDesignerCompletedEventHandler(object sender, LoginDesignerCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginDesignerCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginDesignerCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool LoginDesignerResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool LoginDesignerResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void LoginAdminCompletedEventHandler(object sender, LoginAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoginAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoginAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool LoginAdminResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool LoginAdminResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddDesignInDLCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddShoeCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetOrdersListCompletedEventHandler(object sender, GetOrdersListCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOrdersListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOrdersListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Order[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ShowShoeStatusCompletedEventHandler(object sender, ShowShoeStatusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ShowShoeStatusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ShowShoeStatusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreateaOrderCompletedEventHandler(object sender, CreateaOrderCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateaOrderCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateaOrderCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Order Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Order)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GenerateIdCompletedEventHandler(object sender, GenerateIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GenerateIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GenerateIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int GenerateIdResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool GenerateIdResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void PlaceOrderCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void CreateComplaintCompletedEventHandler(object sender, CreateComplaintCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateComplaintCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateComplaintCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Complaint Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Complaint)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void AddComplaintCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetAllComplaintsCompletedEventHandler(object sender, GetAllComplaintsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllComplaintsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllComplaintsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Complaint[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Complaint[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ApproveAllOrdersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void GetApprovedOrdersCompletedEventHandler(object sender, GetApprovedOrdersCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetApprovedOrdersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetApprovedOrdersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Order[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Order[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.2556.0")]
    public delegate void ClearAllOrdersCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591